---
name: "Code Quality: Packer"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  packer:
    name: Packer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./packer"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Format Packer files
        uses: operatehappy/packer-github-actions@master
        with:
          command: fmt
          target: packer/ubuntu-20.04-hashistack.pkr.hcl

      - name: Validate Packer files
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/ubuntu-20.04-hashistack.pkr.hcl